### ISSUE TITLE
 Got the Syntax error, if tabs and spaces are mixed to indent in Java source code.

### ISSUE THREAD

**Issue by Tand0** [hallvard/plantuml#10]
Hi,

Got the Syntax error, if tabs and spaces are mixed to indent in Java source code.

<pre><code>
////OK code
    ///@startuml
    ///Aaa->Bbb : This indentation is the tab
    ///@enduml

///NG code
    ///@startuml
         ///Aaa->Bbb : This indentation is space
    ///@enduml
    //
</code></pre>

I want net.sourceforge.plantuml.text.TextEditorDiagramTextProvider was skipped the leading spaces and tabs of linePrefix.
I have attached the amendment .

[suggestcode.zip](https://github.com/hallvard/plantuml/files/305028/suggestcode.zip)

Best regards, Ando.

**Comment by hallvard** [comment]
This is similar to issue #9, and the fix I have should handle your case, too. It essentially trims the prefix and line, before checking whether the line starts with the prefix.

**Comment by hallvard** [comment]
It should be fixed now.
