### ISSUE TITLE
Add source features to update site

### ISSUE THREAD

**Issue by fipro78** [hallvard/plantuml#104]
It is a common pratice to also provide source features so users are able to debug. For companies it is also often needed to perform source scans on the integrated versions.

IMHO it shouldn't be a big effort to also provide a source feature by using the tycho-source-plugin and adding a source feature project.

**Comment by hallvard** [comment]
Good point, I've made it work now! Will be available in the next release.

**Comment by fipro78** [comment]
Thanks a lot! I planned to provide a pull request but wasn't able to find some time to contribute until now. Great that you found the time already. :)
