### ISSUE TITLE
License issues with jlatexmath

### ISSUE THREAD

**Issue by fipro78** [hallvard/plantuml#106]
Hi,

I just wanted to let you know that the Eclipse Legal Team found some license issues at least in the jlatexmath bundle.

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21795

We do not use jlatexmath, so for us it is no big issue. Especially since you separated it cleanly from the rest. I just wanted to let you know in case it becomes an issue for others.

**Comment by hallvard** [comment]
The technical solution with a fragments and a separate feature should avoid "contamination" of the rest of PlantUML.
