### ISSUE TITLE
mark abstract super class as abstract in classdiagram

### ISSUE THREAD

**Issue by Snap252** [hallvard/plantuml#108]
having some classes in one files:
```
abstract class X {
    boolean x;
}

class Y extends X {
    boolean y;
}

class Z extends X {
    boolean z;
}

class A {}
```
will result in a **non**-abstract super class X
![1](https://user-images.githubusercontent.com/10380619/81569795-08ce2700-93a0-11ea-8f48-8eace32f134b.png)

expected to be this:
![2](https://user-images.githubusercontent.com/10380619/81570169-83974200-93a0-11ea-9a70-626d06f7026b.png)

When having a look at _PlantUML Source_ there seems to be double generation of the class and maybe last (that is non abstract) wins

**Comment by hallvard** [comment]
Good catch (although it's not recommended to have many classes in a single file)! Without having looked at my code, I guess it's due to not registering classes while processing the file (only afterwards), hence a lookup of the superclass will not find it. Should be easy to fix.

**Comment by arnaudroques** [comment]
This seems to work with last version
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKfCAYufIamkKKZEIImkLeXGgEPI08Aa_FoSrCGyXGgkMYukY5IaGcf5IMfU2gQYIeIYA9oAgX2A71MgQxaSWAg03W00

**Comment by hallvard** [comment]
The plantuml renderer is good at combining elements from several "declarations", so it seems the last version fixes what I would consider a bug in my diagram generator.

**Comment by Snap252** [comment]
Thx for the **very** fast response 😄  - I was wondering little bit if this project is still alive due to less commits.

Of cause it is mostly not good to have multiple classes in a file, but it was the easiest way to reproduce my problem (same behavior inside a selected package - I think)
