### ISSUE TITLE
Plugin does not work in XML files

### ISSUE THREAD

**Issue by hcw70** [hallvard/plantuml#117]
When having a plantuml file within a dita (xml) file, and opened in the eclipse XML editor, no redraw of the plantuml view is happening.
When opening the same file with the eclipse text editor, the plugin works.
Example file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="testPlantUML">
    <title>Test diagram</title>
    <body>
        <p>
            <foreign outputclass="embed-plant-uml">
@startuml
                Alice -> Bob: Authentication Request
                Bob --> Alice: Authentication Response
                
                Alice -> Bob: Another authentication Request
                Alice &lt;-- Bob: Another authentication Response
@enduml
                    </foreign>
        </p>
    </body>
</topic>

```

**Comment by hallvard** [comment]
I've added support for so-called multi-page editors that have editors inside tab items (in a tab folder), and this makes the plugin pick up the PlantUML source code. However, since you need to use entities like &lt; it still won't work, since I don't unescape those, yet.
