### ISSUE TITLE
Built-in Functions %upper and %lower not working in Eclipse

### ISSUE THREAD

**Issue by schmidtjano** [hallvard/plantuml#118]
Happy Monday!

I was receiving an "Unknow [sic] built-in function" error when using the functions **%upper()** and **%lower()** and have been informed by a helpful user on [PlantUML Q&A](https://forum.plantuml.net/12557/problems-with-built-in-functions-%25upper-and-%25lower-eclipse) that these functions are only supported in PlantUML from v1.2020.2 (2020-03-01).

Running the Help>Check for Updates feature in Eclipse has no effect on the PlantUML version used by your software, which remains at **1.2019.11** (Sun Sep 22 05:02:15 CDT 2019) (EPL source distribution) Loaded from bundleresource://1436.fwk1150293741/. 

I also tried replacing the PlantUML JAR file in the Eclipse directory C:\Users\mailb\eclipse\modeling-latest-released\eclipse\configuration\org.eclipse.osgi\1436\0\.cp\lib with the latest version, also to no avail. 

Do I have to wait for you to update your software or is there a way I can install the latest **plantuml.1.2020.22.jar** version available on [PlantUML.com](https://plantuml.com/download)? I apologise for this newbie question, but I have only been using PlantUML and Eclipse for 1½ months. 

Many thanks in advance!

Best regards, 

Jan

**Comment by hallvard** [comment]
Currently, the eclipse support for plantuml is provided in several features, one of which is the wrapper of the underlying plantuml.jar. But in this case, I cannot just update that features, since it's incompatible with the main other feature. Hence, it will be part of the next full release.
