### ISSUE TITLE
includes PlantUML GPL instead of PlantUML EPL

### ISSUE THREAD

**Issue by Bananeweizen** [hallvard/plantuml#12]
The PlantUML library is available under different licenses. This Eclipse plugin (which itself has EPL license) should include the EPL licensed JAR (e.g. http://sourceforge.net/projects/plantuml/files/plantuml-jar-epl-8054.zip/download right now) instead of the GPL licensed version. Otherwise the plugin is not usable in companies which enforce strict license policies.

**Comment by hallvard** [comment]
You're right. I've been working on license issues lately. I've now update to using the EPL version of the plantuml jar, which is included in the latest build at http://files.idi.ntnu.no/publish/plantuml/repository/
