### ISSUE TITLE
Possibility to allow external selection of plantuml.jar

### ISSUE THREAD

**Issue by timur-han** [hallvard/plantuml#120]
Hi, 

Thank you for the contribution.

Is it possible to configure plantuml.jar to be used to render the files? Plantuml has sometimes backward compatiblity issues and in such cases, I think it will help us to select the right version.

**Comment by kferrone** [comment]
I am getting a similar issue with too new of a graphviz dot installation. If only I could select my own plantuml jar.

**Comment by hallvard** [comment]
This is too error prone and would require some classpath magic that's difficult to do right in an OSGi context.
