### ISSUE TITLE
Problems exporting PNG/JPG

### ISSUE THREAD

**Issue by AlexanderZhirov** [hallvard/plantuml#123]
When exported to PNG, it is preserved in this format.

![Untitled](https://user-images.githubusercontent.com/37277056/111700423-719cf000-884a-11eb-80c2-81a6529ab9cd.png)

JPG does not save at all. The only working format is SVG.

Works fine in IDE

![image](https://user-images.githubusercontent.com/37277056/111701128-6b5b4380-884b-11eb-9eff-7cfe3cf600ad.png)

PlantUML plugin version 1.2019.11
OS: Solus Linux 4.2
Eclipse Version: 2020-12 (4.18.0)
JAVA version 1.8.0_192

**Comment by hallvard** [comment]
See #114
