### ISSUE TITLE
Issue with update site: "No repository found at http://hallvard.github.io/plantuml/plantuml.lib/1.2020.16"

### ISSUE THREAD

**Issue by steghoja** [hallvard/plantuml#127]
Hey there,
since yesterday, I am getting errors when trying to build an Eclipse project that uses PlantUML as a dependency. This is what Maven says:

```
[ERROR] Failed to resolve target definition /home/jenkins/agent/workspace/build-src-develop-nightly/releng/org.eclipse.capra.releng.target/org.eclipse.capra.releng.target.target: Failed to load p2 metadata repository from location http://hallvard.github.io/plantuml/: Unable to read repository at http://hallvard.github.io/plantuml. No repository found at http://hallvard.github.io/plantuml/plantuml.lib/1.2020.16. -> [Help 1]
```

The error occurs on the build server (https://ci.eclipse.org/capra/job/build-src-develop-nightly/lastFailedBuild/console) as well as on my local machine. It does not matter if the dependency is to PlantUML 1.1.24 or 1.1.25. My target definition reads as:

```
<location includeMode="planner" includeAllPlatforms="false" includeSource="true" includeConfigurePhase="false" type="InstallableUnit">
      <unit id="net.sourceforge.plantuml.feature.feature.group" version="1.1.24"/>
      <repository id="plantuml" location="http://hallvard.github.io/plantuml/"/>
</location>
```

Has anything changed on the update site?

Best,
Jan-Philipp

**Comment by hallvard** [comment]
I have released version 1.1.25 and plantuml lib 1.2031.3 on the update site, it is about to be announced. References to old versions should work, though. I don't think there is any 1.2020.16, though, the last one was 1.2019.11. I did try to release it, but it was incompatible with the eclipse plugin, so it was removed. Perhaps you somehow still have a reference to it?

**Comment by steghoja** [comment]
For what it's worth, I have no reference to a version 1.2020.16 anywhere in my project. I have also not changed anything in my target platform in the past two days that could have broken this.

But I found the culprit:
https://github.com/hallvard/plantuml/blob/1774459c6b491b00404142e07eaeaeb37b2c9ec1/compositeArtifacts.xml#L17

The `compositeArtifacts.xml` reference a version 1.2020.16. Removing that should fix the issue.

**Comment by hallvard** [comment]
Thanks, that went unnoticed! It never triggered any problem in my testing. I've checked in replacements for the tow composite*.xml files.

**Comment by hmackamul** [comment]
Hello,
we got the same error yesterday. @Jan-Phillip: Thanks for reporting and debugging the issue! :-)
(In my case the problem occurred after a bigger target change, therefore I first had a look at my changes)

Best,
Harald

**Comment by steghoja** [comment]
My pleasure, Harald!

I think Maven and Eclipse P2 handle update sites slightly differently: while P2 happily ignores missing features, Maven fails. That's probably why it didn't show up in your testing.

Anyway, it works again, so I am closing this. Thank you very much!
