### ISSUE TITLE
After update to 1.1.25 certain diagrams with Windows' line endings don't render

### ISSUE THREAD

**Issue by Lutz13** [hallvard/plantuml#128]
So far I was able to edit a digram-code in Eclipse text editor (file extension: *.puml), and the diagram was automatically generated and shown in the PlantUML view.
After updating the plugin to version 1.1.25 today, the diagram is no longer generated, whatever I try.
Eclipse:
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

**Comment by hallvard** [comment]
Could you also check the PlantUML source view?

**Comment by danieleb2000** [comment]
For me the same.
Diagram generated only if the text is rewritten from scratch. No diagram is (re-)generated after opening or modifying an existing one.
Only PlantUML source view is correctly updated.

**Comment by hallvard** [comment]
If the source view is updated, we at least know that the views are correctly triggered by changes in the editor, but something must be happening when the text is converted to a diagram. No entries in the Error log view?

I'm a bit confused when you say "rewritten from scratch", do you mean removing and recreating the file, or clearing the editor before reentering the (same) code?

**Comment by danieleb2000** [comment]
If I create a new txt file from scratch, and write @startuml and so on, the diagram is shown.
But if a txt file is preexisting, the diagram is never shown, no matter what content it has  and even after changing it or clearing and paste back the same code. 
With 1.24 this never happens.

**Comment by hallvard** [comment]
I must admit I haven't a clue, as I couldn't reproduce it. Perhaps we could have a screen sharing session with e.g. Teams where you can show it to me.

**Comment by danieleb2000** [comment]
I also tried with the following combination, still same issue:

PlantUML Ecore Feature    1.24
PlantUML Feature          1.25
PlantUML Library        2021

It seems the issue depends on PlantUML Feature 1.25 or PlantUML Library 2021.

Other combinations are not possible since not compatible (according to the update attempt).

**Comment by danieleb2000** [comment]
Probaby one of the following two features for 1.25 introduced the issue:

- Added new extension point that supports generating several alternative diagrams for the same content (issue #109) and **delays the computation of the diagram so it can run on a non-UI thread** (issue #82). Uses of old extension point should still work, but should be updated to use new one.
- I needed to **remove (for now) the feature that recomputes saved diagram images during builds, when their source have changed.**

**Comment by hallvard** [comment]
Diagram generation is split in three. First the intention is provided, this happens on the UI thread. Then the source of the diagram is generated, as a background task. This part apparently works, as the source view updates correctly. Finally, if you need an actual diagram, the image is generated (in the same background task) and the UI is updated (naturally on the UI thread). There's logic to prevent the UI to update when a diagram arrives, if it thinks it is about to overwrite a more recently requested diagram. Perhaps this logic is faulty. But as I said, it works for me, and I would assume it works for most others, as there hasn't been reports other than those in this issue.

BTW, what platform are you on? I'm not sure that should matter, but it's worth noting.

**Comment by danieleb2000** [comment]
Windows 10 64 bits. Tried with both Eclipse 2021 and Eclipse 2019.
1.24 works perfectly on both. 
The only update-diagram trigger that always works with 1.1.25 is just creating a new file from scratch and then editing it.
But in a later session also that file becomes a "preexisting" one and therefore stops to generate a new diagram after being updated.

**Comment by danieleb2000** [comment]
Please see screenshot below.
A diagram text is updated and the Tab PlantUML Source shows it correctly, but the PlantUML diagram TAB is stuck to a previous diagram.

![image](https://user-images.githubusercontent.com/38882361/115689809-b8579b80-a35c-11eb-97b8-2c389031b30b.png)

**Comment by hallvard** [comment]
That's so strange, when an editor opens and triggers my listener, the listener doesn't know whether the file is new or not.
It seems a bit strange that the source doesn't include the @enduml line, perhaps that's important. If it's not part of what's sent to the underlying plantuml library, generating the actual diagram won't work!

**Comment by danieleb2000** [comment]
That's the point. 
I confirm: the diagram is updated only if @enduml is shown in the Source view, which is often not the case...

**Comment by danieleb2000** [comment]
I think I understood where the problem is. 
@enduml is shown only if it is the last line, or at least if there is no empty line after. But even with empty lines after, the diagram should still be valid...

**Comment by danieleb2000** [comment]
By the way, also <math> formulas are not shown anymore.

**Comment by hallvard** [comment]
If you can experiment and identify the precise conditions for when the ending @enduml is missing, it will be very helpful!

Please open another issue for the math formulas.

**Comment by danieleb2000** [comment]
Simply:   
@enduml is missing always if it is **not on the last line of the file**

**Comment by hallvard** [comment]
A cannot reproduce this in either my development eclipse (Eclipse 2020-6) or Luna (the target), sorry.

**Comment by danieleb2000** [comment]
Crazy. Did you try with a file where @enduml is followed by some empty lines?
Maybe this is due to the encoding of empty lines (Dos vs Unix)?

**Comment by hallvard** [comment]
Yes, tried with lots of combinations of nothing, whitespace and stuff. Encoding of line endings may have something to do with it.

**Comment by danieleb2000** [comment]
Yes, it seems to be the reason! 
Lines ending with "\r\n" after @enduml generates this issue (Windows newline)
With lines ending only with "\n" after @enduml the tool works

**Comment by danieleb2000** [comment]
Probably lines **after** @enduml does not play any role; the real issue is if the newline on the same line of @enduml is "\n" instead of "\r\n".
But "\r\n" is the End Of Line on a windows platform.

**Comment by hallvard** [comment]
In general I'm used to java converting line endings from platform specific ones to just \n, but that might not be happening when I use the editor (Document) API. I can see if there are places where I look for @enduml (or other tags) followed by just \n. Maybe I can replace that with the platform line ending. It's a bit difficult for me to test, though, since I don't use or have a windows computer. But I may be able to at least insert a \r before the \n to see why/where it fail.

**Comment by hallvard** [comment]
Note to self: IDocument has a **getLineDelimiter(int line)** method that maybe should be used in TextDiagramIntentHelper for normalising the end of line, so most code can expect to see only \n

**Comment by Lutz13** [comment]
When I open or switch windows to a textfile (extension .puml) that contains PlantUML code, it works fine.
When I open or switch to a java code files, I get the attached error message
![Error](https://user-images.githubusercontent.com/53346587/118395983-9f859180-b64d-11eb-9b65-018307262776.png)

**Comment by hallvard** [comment]
Ok, so the original problem seems to be solved. This particular error message is due to work on a new feature, that wasn't finished when publishing the snapshot. I'll release 1.1.26 soon with fixes for both.

**Comment by Lutz13** [comment]
Great, thank you!
