### ISSUE TITLE
New empty lines before @startuml or after @enduml 

### ISSUE THREAD

**Issue by zieglerz** [hallvard/plantuml#134]
Hi,
I updated your PlantUML plug-in from version **1.1.24** to **1.1.25** (I also migrate whole Eclipse from 2020-03 to 2021-03) and unfortunately for some of our puml files render stopped working in PlantUML view.

After investigation we found the root cause of this issue. **When we add empty lines before `@startuml` or after `@enduml` render stop working without any error message.**

Could it be handled in upcoming version as bugfix, please? :)

Thank you in advance!
Best regards
Ziegler

**Comment by hallvard** [comment]
I've identified a problem with incorrect handling of platform-specific line separators, see #128. Could it be the same issue you experience?

**Comment by zieglerz** [comment]
So If I understand it correctly you suggest to update to the snapshot version, right? :)

**Comment by zieglerz** [comment]
Great, update helped! Thank you for super fast reply! :)

**Comment by zieglerz** [comment]
Hello again, 
the initial bug was fixed. But another tricky one appeared.  There was a same problem once we forgot a whitespace after `@enduml` .  Could it be also handled in the future, or are whitespaces hard to handle in given syntax? (I do not work with puml so I do not know it much, I just manage Eclipse for our team. :) )
