### ISSUE TITLE
Whitespace after @enduml

### ISSUE THREAD

**Issue by zieglerz** [hallvard/plantuml#135]
Hello again, 
the initial bug from issue #134 was fixed. But another tricky one appeared.  There was a same problem once we forgot a whitespace after `@enduml` . Could it be also handled? 

Thank you in advance
Best Regards
Ziegler

_Originally posted by @zieglerz in https://github.com/hallvard/plantuml/issues/134#issuecomment-855844542_

**Comment by nayankhare** [comment]
Trying to install the PlantUML 1.1.24 version in Eclipse Version: 2021-06 (4.20.0).

Problem: http://hallvard.github.io/plantuml/ points to 1.1.25 when trying to install the Plugin when following the below step in Eclipse:
Go to Help/Software Update/Find and install... or Help/Install new software...

Is there a way to get the 1.1.24 version installed for Eclipse Version: 2021-06 (4.20.0).

**Comment by hallvard** [comment]
Uncheck the box "Show only the latest version..."

**Comment by hallvard** [comment]
I'm not going to give priority to fixing this, you could try using a save action to clear trailing whitespace.
