### ISSUE TITLE
java.lang.ArithmeticException: / by zero (produced for links in diagrams)

### ISSUE THREAD

**Issue by anthonyanjorin** [hallvard/plantuml#139]
![image](https://user-images.githubusercontent.com/6302793/133771721-a850a9e5-f7c7-4b36-8203-4180ed6eb221.png)

I am currently attempting to update my Plantuml Eclipse plugin and to switch to the new DiagramIntentProviders.
I don't know what is causing the problem but everything worked fine before and now my links in documents are no longer working (see exception above).

The code appears to be problematic anyway -- as the variables are all ints the division is integer division which is always a bit strange.   In the current case `minX` is 6, `marginX` is 7, `sx` is 0 and BOOM.

**Comment by hallvard** [comment]
So you have empirical evidence that marginX = 7 is wrong. I agree that I anyway should check for the division by zero case.

**Comment by travkin79** [comment]
Seems to be fixed in release 1.1.27
