### ISSUE TITLE
DiagramTextProvider.supports*() methods are never called

### ISSUE THREAD

**Issue by steghoja** [hallvard/plantuml#140]
Starting from 1.1.25, the `supportsEditor()`, `supportsView()`, and `supportsSelection()` methods are no longer called. The `DiagramTextIntentProvider` gets the text from the `DiagramTextProvider` without checking these methods first. That means that a `DiagramTextProvider` implementation could provide bogus diagram text that is not suitable for the current selection.

Another side effect is that the diagram gets overwritten when focus switches to the PlantUML view. This makes navigating that view almost impossible.

I can reliably reproduce this issue with Eclipse Capra when switching from 1.1.24 to 1.1.25 or 1.1.26, so I'd consider this a regression.

**Comment by travkin79** [comment]
Seems to be fixed in release 1.1.27
