### ISSUE TITLE
PlantUML diagram not generated with 1.1.26

### ISSUE THREAD

**Issue by JosHouwen** [hallvard/plantuml#143]
I am happily jusing PlantUML in Eclipse already for many years.
I wanted to updated the Eclipse plugin from 1.1.24 to 1.1.26
But there in the viewtab : PlantUML the image was not generated anymore.
I also found a new viewtab : PlantUML Svg where the image is generated, but copy this images adds a zoom in the image

How can I enable the viewing in the PlantUML view tab

![image](https://user-images.githubusercontent.com/59705468/136662814-f76ac04a-3345-4e7c-93c8-e6125a69d1af.png)

**Comment by hallvard** [comment]
I think this is a bug reported earlier, see issue #139, that I recently reproduced and fixed. I'm preparing a new release but cannot promise when.
