### ISSUE TITLE
why failure in installing plantuml plugin in eclipse IDE? 

### ISSUE THREAD

**Issue by PiperWei** [hallvard/plantuml#144]
eclipse version : 
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

**I use eclipse's tool to install:
Go to Help/Software Update/Find and install... or Help/Install new software...
Create (if needed) or choose the following site as update site: http://hallvard.github.io/plantuml/

but, it failured:
I cat't upload the picture because of internet performance.  the detail is:**

**************************
Cannot complete the install because one or more required items could not be found.
  Software being installed: PlantUML Feature 1.1.26 (net.sourceforge.plantuml.feature.feature.group 1.1.26)
  Missing requirement: PlantUML Java Support 1.1.26 (net.sourceforge.plantuml.jdt 1.1.26) requires 'java.package; org.eclipse.jdt.internal.debug.core.model 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: PlantUML Feature 1.1.26 (net.sourceforge.plantuml.feature.feature.group 1.1.26)
    To: org.eclipse.equinox.p2.iu; net.sourceforge.plantuml.jdt [1.1.26,1.1.26]
***********************

**how  I can resolve this problem, thanks!!!!**

**Comment by PiperWei** [comment]
who  can  give  me  some  tips?thanks

**Comment by hallvard** [comment]
This may be because the PlantUML plugin refers to an internal package (org.eclipse.jdt.internal.debug.core.model) and that package has been removed or renamed in the latest Eclipse. I'll have to download that Eclipse and see for myself.

**Comment by PiperWei** [comment]
ok，please give  me  some tips if any progess,I really need plantuml  in  eclipse,thanks!



This may be because the PlantUML plugin refers to an internal package (org.eclipse.jdt.internal.debug.core.model) and that package has been removed or renamed in the latest Eclipse. I'll have to download that Eclipse and see for myself.

**Comment by hallvard** [comment]
The package org.eclipse.jdt.internal.debug.core.model is indeed imported by net.sourceforge.plantuml.jdt, but I cannot find any references to it in the code! I think the import was added when I looked into visualising stack object structures in the variables view as object diagrams. This requires that model, I believe. 

I'll see what happens if I remove the import. I'll likely try to release a new version pretty quickly if it works.

**Comment by PiperWei** [comment]
This is really good news, thank you for your help，
 and at the same time, I will always wait for your new version of the program

**Comment by PiperWei** [comment]
Hi, is there any progress?

**Comment by PiperWei** [comment]
> The package org.eclipse.jdt.internal.debug.core.model is indeed imported by net.sourceforge.plantuml.jdt, but I cannot find any references to it in the code! I think the import was added when I looked into visualising stack object structures in the variables view as object diagrams. This requires that model, I believe.
> 
> I'll see what happens if I remove the import. I'll likely try to release a new version pretty quickly if it works.

Hi, is there any progress?

**Comment by travkin79** [comment]
Seems to be fixed in release 1.1.27
