### ISSUE TITLE
typo in generated plantuml code for inheritance relationship

### ISSUE THREAD

**Issue by jzniu** [hallvard/plantuml#162]
The plantuml source code embedded in exported svg files have "<|- -" (extra space) instead of "<|--".

I tried to reproduce svg using the embedded source code on planttext.com as the svg exported from the eclipse plugin shows part of the diagram when opened in a browser.

**Comment by hallvard** [comment]
The contents of the export svg is handled by the underlying plantuml.jar, so you need to contact its author.
