### ISSUE TITLE
exported svg file showing only a partial diagram

### ISSUE THREAD

**Issue by jzniu** [hallvard/plantuml#163]
svg view works fine but exported svg file doesn't show entirely when opened in my browser. Please see the attached screenshots.

OS: Windows 10 x64
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112

plugin version shown in attached screenshot

![Screenshot 2022-09-07 014705](https://user-images.githubusercontent.com/6538395/188798327-a0b4c54d-5627-486a-b7c5-8afd9b63efd0.png)
![Screenshot 2022-09-07 014645](https://user-images.githubusercontent.com/6538395/188798329-e2d429f3-9a65-4d60-a177-16a6d1b4d25c.png)
![Screenshot 2022-09-07 015043](https://user-images.githubusercontent.com/6538395/188798765-eeb91981-143b-4d00-a2bc-4ce7c2d24301.png)

**Comment by hallvard** [comment]
The contents of the export svg is handled by the underlying plantuml.jar, so you need to contact its author.
