### ISSUE TITLE
Colors missing

### ISSUE THREAD

**Issue by mnlipp** [hallvard/plantuml#171]
I'm not sure, when this happened, but until "recently" diagarams used to be rendered with colors (as you see them on the PlantUML site). But now the diagrams in the PlantUML window have a gray background. Can I change this back "to normal"?

**Comment by travkin79** [comment]
I think, that comes from the new PlantUML lib version. PlantUML changed the default diagram style. The default colors are gray, not yellow and red anymore. I'm not sure if you can change the PlantUML default style, but you can change the style per diagram (see PlantUML docs, e.g. [themes](https://plantuml.com/de/theme) and [styles](https://plantuml.com/de/style-evolution)).

I'd say, it's a feature, not a bug. ;-)

**Comment by mnlipp** [comment]
Thanks for the clarification.
