### ISSUE TITLE
Generate class-diagram without methods.

### ISSUE THREAD

**Issue by jakobklein** [hallvard/plantuml#174]
The feature to create a class-diagram in Eclipse by selecting a package is great! Can I configure the PlantUml-Eclipse-Plugin to show just the classes and hide methods and fields?
I read in multiples locations that I can configure the plugin via plugin via a properties file but did not find a reference of the valid configuration-properties or any information where the propterties file should be located or how it must be named.

Thx!

**Comment by travkin79** [comment]
I didn't find out where the properties files have to be placed, but I found the properties documentation in the GitHub project here:
https://github.com/hallvard/plantuml/blob/master/releng/net.sourceforge.plantuml.parent/Customization.md

I think, you could try [injecting PlantUML diagram text](https://github.com/hallvard/plantuml/blob/master/releng/net.sourceforge.plantuml.parent/Customization.md#injecting-diagram-text) for [hiding attributes and methods](https://plantuml.com/en/class-diagram#6a8ec84e53ede3ae), i.e. according to the docs, something like the following should do the trick.

```properties
java.path = ....java
java = hide members
```

**Comment by jakobklein** [comment]
Great. This worked and got me the result I wanted. Thx a lot!

**Comment by jakobklein** [comment]
Not mentioned in Customization.md:
For multiple show/hide commands you have to chain them with a newline charactert, e.g.

    # Include fields, hide methods and hide all extended interfaces named "CrudRepository" (The * because PlantUml adds a suffix to the name of an implemented interface)
    java.path = ....java
    java = show fields\nhide methods\nhide CrudRepository*

**Comment by swm123456** [comment]
@jakobklein Do you mind sharing how you managed to get customization to work? I'm trying to do a similar thing but confused with where the .properties files are placed and how are they organized. Thanks!

**Comment by jakobklein** [comment]
@swm123456 Sure! It took me a while to figure out the following

1. Given you have a project "testproject" in your workspace with a subfolder "myconfig"
2. Create a file there with the exact name DiagramTextInjectionPostProcessor.properties
3. Content for a java-project may be:
`java.path = ....java
java = show fields\nhide methods\nhide CrudRepository*`
4. Go to Preferences > PlantUML > Diagram generation > "Diagram generation settings folder" and set it to `/testproject/myconfig`
