### ISSUE TITLE
Generate diagram for a whole project

### ISSUE THREAD

**Issue by arnaudroques** [hallvard/plantuml#18]
It would be nice if the plugin could generate a diagram for a whole Eclipse project.
(related to http://plantuml.sourceforge.net/qa/?qa=5537/how-can-nested-classes-interfaces-be-represented )

**Comment by hallvard** [comment]
I've pushed some initial code for this. I've added a new view (PlantUML Project Class Diagram) that is populated from what you drag into it from the Package or Project Explorers, not what's in the active editor. The view collects all types within the nodes you drag'n drop and renders a diagram with them (and related classes). We should now discuss more detailed behaviour, including what options could/should be added and what defaults to use.

**Comment by krooq** [comment]
First thing I noticed when using this was that packages are not implemented.  It would be nice to have packages as an option.
Beautiful plugin btw, I love it!

**Comment by hallvard** [comment]
You mean wrap the classes in a diagram in package rectangles/folders? When you say "option", how would you prefer providing it, as a preference in the general preference dialog or elsewhere, e.g. dialog activated from the view itself?

**Comment by krooq** [comment]
Yep, exactly as you can do with plant uml.  I find that providing packages in a UML diagram can help to quickly show the structure of the diagram. 

General preference dialog in eclipse would be preferable I think.  Most people know to look there to change settings.

**Comment by hallvard** [comment]
Should be in the next release, this month. You can toggle package generation and select the visual style.
