### ISSUE TITLE
add "Open" and "Show In" buttons for resource selection

### ISSUE THREAD

**Issue by anb0s** [hallvard/plantuml#22]
Related to #21: additionally it would be perfect to have "Jump to" or "Open" and "Show In" buttons that puts to front or opens the resource editor or selects the pinned resource in Project Explorer.

**Comment by hallvard** [comment]
I'm reluctant to add many more buttons. Would it be OK to just open the resource/bring it to front if you select a plantuml view that is pinned? Then the Project Explorer should follow if it is linked to the current editor.

**Comment by anb0s** [comment]
Yes, i see, it would be OK too.

I'm just curious if it's also about the "double arrow" button:
- in PlantUML view it says "Activate/deactivate generation of diagram"
- in other Eclipse views it says "Link with ..." and has the behavior like you describe here

**Comment by hallvard** [comment]
Yes, I should update the text so it's consistent with other Eclipse views, e.g. "Link with Editor".

**Comment by paulvi** [comment]
Not that "Link with Editor" links with a file, not a particular diagram within it https://github.com/hallvard/plantuml/issues/64

**Comment by hallvard** [comment]
It links to an editor for a file, so the diagram will change with the selection. I could add a "locked" mode, where it never updates (until the "locked" mode is exited).

**Comment by paulvi** [comment]
"locked" mode is already there, just pin and disable "Link with Editor"
