### ISSUE TITLE
add drag and drop support of resources to PlantUML view

### ISSUE THREAD

**Issue by anb0s** [hallvard/plantuml#23]
Related to #21: sometimes during writing PlantUML comment in one component i want to see a diagram from other component without opening the related resource in an editor first, because then i have to do multiple steps: open the other component resource in editor, create new PlantUML view, wait for generating diagram and pin the view to it.

The new workflow would be:
- open/create a view and work with actual diagram
- create new PlantUML view
- drag and drop the resource from Project Explorer to new PlantUML view
  - in this case the view should generate the diagram and pin the view to the dropped resource
  - or report error if no @startuml command found etc.

**Comment by hallvard** [comment]
I've already created a new view that supports drag'n drop like this, that does not track the currently active editor. Perhaps I can combine that in a sensible way, so I don't need two views. This view supports dragging a whole project or package, which does not make sense to pin. In that case I can deactivate linking to the editor (the double arrow that previously was a traffic light).

**Comment by anb0s** [comment]
OK, it sounds good, but it may make it more heavy then and leads to more complicated implementation...
