### ISSUE TITLE
Add enhancement to support new hyperlink syntax in sequence diagrams.

### ISSUE THREAD

**Issue by jparker324** [hallvard/plantuml#24]
See http://plantuml.com/link

@startuml
actor Bob [[http://plantuml.com/sequence]]
actor "This is [[http://plantuml.com/sequence Alice]] actor" as Alice
Bob -> Alice [[http://plantuml.com/start]] : hello
note left [[http://plantuml.com/start]]
  a note with a link
end note
Alice -> Bob : hello with [[http://plantuml.com/start{Tooltip for message} some link]]
note right [[http://plantuml.com/start]] : another note
note left of Bob
You can use [[http://plantuml.com/start links in notes]] also.
end note
@enduml

**Comment by hallvard** [comment]
Good idea! Apparently, there is support image maps: "The API is not really good but you can have
location/size/link of element calling the following method of SourceStringReader.java :
getCMapData(int numImage, FileFormatOption)
Set the first argument to 0 and the second to new FileFormatOption(FileFormat.PNG)
This method returns a String you will have to parse, with all data inside.
Tell me if you have some issues and if I can improve this."

Will be supported in next release. The only issue was the cursor, currently the hand is used for panning, but with hyperlink support, it makes more sense to use the hand to indicate a link. Hence, I'll use the ordinary pointer for panning (unless there are other good suggestions).
