### ISSUE TITLE
State Diagram incorrect rendering issues

### ISSUE THREAD

**Issue by jparker324** [hallvard/plantuml#29]
Using the test text below, I have included two issues that I have observed.  I apologize for the complexity of the test case, but I reduced it as much as possible where I could.

@startuml
title test for improper rendering

[*] --> s0

state group0{
    s0 -right-> s1: o
    s1 --> s2 : p
    s1 --> s3 : q
    s2 --> s1 : r
    s3 --> s1 : s
    s2 --> s3 : t
}

state group1{
    s0 --> s4 : a
    s4 --> s7 : b
    s7 --> s8 : c
    s8 --> s5 : d
    s5 --> s7 : e
    s9 --> s7 : f
    s8 --> s7 : g
    s8 --> s6 : h
    s6 --> s8 : i
    s6 --> s6 : j
    s5 --> s6 : k
    s6 --> s5 : l

    'ISSUE 1
    'this line works
    s8 --> s8 : a\nb
    'but this next line causes a dot.exe error when using the eclipse plugin.  Running the plantuml.jar file from outside eclipse renders te line fine.  It seems to be related to the second newline and not the length of the text
    's8 --> s8 : a\nb\nc
}

group1 --> s1 : m
group0 --> s7 : n

'ISSUE 2
'this next transition line when uncommented causes the group1 box to become large and then renders the transition arrow, but not the text for the transition
'to be clear the .jar file also incorrectly sizes the group1 box, but it does render the text to the right of the arrow.
'group1 --> group1 : sample text that is not rendered and the width of the group1 to the left is expanded proportionally to the length of this text.............................

@enduml

Reference info just in case...

  PlantUML Ecore Feature	1.1.14.201703160918	net.sourceforge.plantuml.ecore.feature.feature.group	PlantUML Team
    PlantUML Feature	1.1.14.8059	net.sourceforge.plantuml.feature.feature.group	PlantUML Team
    PlantUML Library Feature	1.1.14.8059	net.sourceforge.plantuml.lib.feature.feature.group	PlantUML Team

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is c:\Program Files (x86)\Graphviz2.38\bin\dot.exe
Dot version: dot - graphviz version 2.38.0 (20140413.2041)
Installation seems OK. File generation OK

**Comment by hallvard** [comment]
Can you check the source view, and see if it gives any clue to what's going on? It should show what source source text is passed to the library.

**Comment by jparker324** [comment]
If I uncomment the line, it simply shows the line as I have it above but without the quote ' character.
when the dot.exe crashes, the PlantUML window says this...

**test for improper rendering**
An error has occured!
_<some funny text here>_

For some reason, dot/Graphviz has crashed.
This has been generated with PlantUML (7997).

You should send this diagram and this image to **plantuml@gmail.com** to solve this issue.
You can try to turn arround this issue by simplifying your diagram.

**Comment by hallvard** [comment]
Does this also happen in the PlantUML source view?

**Comment by hallvard** [comment]
The last comment was a mistake... I'll check it out after the Easter-holiday. In the meantime, could you try the latest release?

**Comment by jparker324** [comment]
The "PlantUML Source" view always looks like a true interpretation of the original text.  All the errors seem to be in the rendered image "PlantUML" view.  Also, I'm not ruling out it's something local in my system or setup.  I have not had a colleague confirm the defect.

**Comment by arnaudroques** [comment]
> This has been generated with PlantUML (7997).

It looks like you have an old version of PlantUML.

Your example seems to work on the online server:
http://www.plantuml.com/plantuml/uml/NP4_JyCm4CNtzobkYuGKAU4_7L0N1kQAYJAahPkO9dOuNyM0-EwS4t4HJ4-_U-TxFdkTf64v3pt4I-z8N18wHYO_Z1n7nyGk71pxq0Al5szKbe-KAa3FYQEMutcilf0gAjctdMItNb54gkVMIrhHQ7Ibz04jJbGhCRHebCpBdOBlFq7r79JjQxKRg4nqfxI3oaJtIdkeJ7IZT82ATJgaXuMErfcfDRfLwg1YCxrHzjvjPgQJUJcl1uhdpURbYMeKqlb4lG-EFYEV4ehVX3opsOOT_XUsOO-y-hpqyZh3NAcMwmQizNlq-tu0

Could you try to update your plugin ?
Thanks

**Comment by jparker324** [comment]
This was the solution.  I had tried to update to the latest version before, but I had another plugin with the older version of PlantUML that it was using first for some reason.  I re-updated and removed the other plugin manually and now both issues are resolved.  The "group1" box is still oversized, but that's clearly not an issue with the Eclipse plugin.  Thanks for your help.

  PlantUML Ecore Feature	1.1.17.201704061657	net.sourceforge.plantuml.ecore.feature.feature.group	PlantUML Team
    PlantUML Feature	1.1.17.201704061657	net.sourceforge.plantuml.feature.feature.group	PlantUML Team
      PlantUML Library Feature	1.1.17.8059	net.sourceforge.plantuml.lib.feature.feature.group	PlantUML Team
