### ISSUE TITLE
"copy source code" API 

### ISSUE THREAD

**Issue by KyrilLekarski** [hallvard/plantuml#3]
When using Plantuml under Eclipse, it is possible to right click on a plantUML diagram and the then select “copy source code”. I’m developing an eclipse plug that use plantUML plug-in. From your point of view, is it possible to get automatically the “source code” by calling plantUML plug in from my java plug-in ?

**Comment by hallvard** [comment]
Hi,

Thank you for your interest in the PlantUML plugin. I don't think there 
is API specifically for this use case, but it can surely be done. You 
can look at the source code here:
https://github.com/hallvard/plantuml/tree/master/net.sourceforge.plantuml/src/net/sourceforge/plantuml/eclipse

Please suggest changes, by email or with a pull request, and we will 
consider it! Other suggestions are also welcome.

Hallvard

On 27.03.15 17:42, KyrilLekarski wrote:
> When using Plantuml under Eclipse, it is possible to right click on a
> plantUML diagram and the then select “copy source code”. I’m developing
> an eclipse plug that use plantUML plug-in. From your point of view, is
> it possible to get automatically the “source code” by calling plantUML
> plug in from my java plug-in ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hallvard/plantuml/issues/3>.
>

-- 
Hallvard Traetteberg, Associate Professor
Dept. of Computer and Information Sciences (IDI)
Norwegian University of Science and Technology (NTNU)
