### ISSUE TITLE
Inconsistancy in handling enum within Project Class Diagram

### ISSUE THREAD

**Issue by damienwojtowicz** [hallvard/plantuml#30]
I noticed that enum management within Project Class Diagram is wrong. Enum seems to be considered as a class and its litterals as unary associations.

Here is an example:
```Java
package misc;
public enum Jour {
	LUNDI, 
	MARDI, 
	MERCREDI, 
	JEUDI, 
	VENDREDI, 
	SAMEDI, 
	DIMANCHE
}
```

Here is a snippet of the project class diagram:

![bug](https://cloud.githubusercontent.com/assets/9526908/25003828/93253fc6-2051-11e7-8767-05ff3d8392ea.png)

Here is the generated PlantUML code:

```
enum Jour [[/MyProject/src/misc/Jour.java]] {
}
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : LUNDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : MARDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : MERCREDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : JEUDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : VENDREDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : SAMEDI
class Jour [[/MyProject/src/misc/Jour.java]] {
}
Jour --> "1" Jour : DIMANCHE
```

This is obviously a problem occuring in PlantUML Project Class Diagram View, since "simple" PlantUML view shows the following enum, which is correct:
![jour](https://cloud.githubusercontent.com/assets/9526908/25003898/dbc3833c-2051-11e7-9f72-999ee0451442.png)

**Comment by hallvard** [comment]
The code that generates associations didn't check that the field is an enum, for which associations shouldn't be generated. The ordinary PlantUML view doesn't try to show associations to other classes, so it wasn't hit by the bug.
