### ISSUE TITLE
java: URI for links to java classes potentially without source

### ISSUE THREAD

**Issue by hallvard** [hallvard/plantuml#31]
The platform scheme can be used to link to classes within eclipse, but only if you know the path. A java scheme could be used to link to any java class, and using org.eclipse.jdt.internal.debug.ui.actions.OpenTypeAction to find the path.

**Comment by hallvard** [comment]
Supported syntax: java:/<fullyQualifiedClassName>[#<memberName>]. Couldn't use java: without /, since the PlantUML library didn't recognize it as a proper link.

**Comment by hallvard** [comment]
Defined extension point to avoid dependency to jdt in generic link handling code.

**Comment by arnaudroques** [comment]
Do you wish that the PlantUML library supports syntax [[java:linkWithoutStartingSlash]] ?

**Comment by hallvard** [comment]
Yes, it would be nice if the library supported the more generic URI syntax, which allows java:linkWithoutStartingSlash!

**Comment by arnaudroques** [comment]
I'm getting confused because the following example is working for us:
```
@startuml
class Car {
  Some field [[[java:link1]]]
  Some method() [[[java:link2]]]
}
class Car [[java:link3]]
@enduml
```

Could you give a non-working example ? Thanks!

**Comment by hallvard** [comment]
**class Links [[java:java.lang.String]]** didn't work, but **class Links [[java:/java.lang.String]]** did.

**Comment by hallvard** [comment]
My mistake, some other code choked when the URI didn't have a path and stopped the java link without slash from working!
