### ISSUE TITLE
!include fails on export and printing

### ISSUE THREAD

**Issue by SieDa** [hallvard/plantuml#35]
The export and printing is not supporting !include files. 
While the preview is showing the results, the export and printing provides an error output:
 Error Message: Cannnot include c:\eclipse\ ... \style.plantuml, while I'm not using an explicit path
and work in a Workspace on s: and the absolut path of eclipse should not be used here, just my .\style.plantuml .

I tested that in 1.1.19 on eclipse Luna. Looks like the relative path is not used in eclipse. 
Updated from 1.1.8 because of newpage support #11.

**Comment by SieDa** [comment]
My sequence diagrams start with lines like this, where "proj-" is customer related or empty:  

@startuml
!include proj-style.plantuml
...
@enduml

**Comment by hallvard** [comment]
This is a newly introduced bug, I think. The export (unless SVG is the output format) and print (and copy) actions are not supposed to regenerate an image, instead they should export or print the currently shown image. Instead, they regenerate and without setting the current path, hence the problem (I think).

**Comment by SieDa** [comment]
You can try with any (sequence) diagram and put a few lines into an !include and place it into the same workspace (sub) directory. It references it to the eclipse and not to the workspace directory.  
The output only contains the error message with the wrong reference. 
Between 1.1.8 out of the Standards  eclipse.org plantuml and your newpage supporting version there must be the change for this.  May be that helps to find it somewhere in the middle of that change history. 

Love your 'newpage' (see enhancement comment 2. on #11), but need Output ;-)

**Comment by hallvard** [comment]
The fix I've made for export (and print and copy), that makes sure it exports (or prints or copies) the currently shown image, also fixes the include issue. I'll notify you when I have a big fix release ready.

**Comment by SieDa** [comment]
Is the fix available yet - somewhere - how do I find out?

**Comment by hallvard** [comment]
The fix is pushed to GitHub, but not released (see the README in the repo, which includes entries for the unreleased v. 1.1.20). I'll likely make a 1.1.20 snapshot release available soon.
