### ISSUE TITLE
HOW Update PlantUML 7997 to 8029

### ISSUE THREAD

**Issue by SofiaIgnacia** [hallvard/plantuml#4]
Dear ...

I'm using the Eclipse' plugin and I have a problem with the statement "detach". I think I have to update PlantUML, but I don't know how to do it. Could you help me, please?

Thanks
Sofia.

**Comment by xxxtonixxx** [comment]
+1

**Comment by tjallingran** [comment]
When using the regular PlantUML Eclipse update site, the version of PlantUML can apparently be updated simply by replacing the PlantUML .jar file, as stated [here](http://plantuml.sourceforge.net/qa/?qa=4651/how-to-install-newest-eclipse-plugin-of-plantuml).

I'd assume that this would work here as well (but haven't tested this)

**Comment by hallvard** [comment]
I've now updated the jar to 8054. In the future, I'll try to make it easier to update just the feature containing the jar.

**Comment by xxxtonixxx** [comment]
Thanks @hallvard for your effort 👍
