### ISSUE TITLE
Plantuml eclipse plugin crashes when I try using inline <math></math>

### ISSUE THREAD

**Issue by boshka** [hallvard/plantuml#45]
Please see http://forum.plantuml.net/6972/plantuml-eclipse-plugin-crashes-when-using-inline-math-math for details.
Example code:
@startuml

legend

<math>CRC(T) = sum_{i=1}^{N_T} CRC_i</math>

endlegend

@enduml

**Comment by hallvard** [comment]
I use the plantuml jar file provided by the plantuml author. If some part of feature is missing, it's probably due to licensing issues.
