### ISSUE TITLE
Update Site down

### ISSUE THREAD

**Issue by RolandKluge** [hallvard/plantuml#48]
I am not able to reach the official update site under

http://files.idi.ntnu.no/publish/plantuml/repository/

**Comment by hallvard** [comment]
Do you see the directory listing if you open the URL in a browser? Perhaps the server has been configured to not allow connections from outside our campus...

**Comment by RolandKluge** [comment]
The error message in Firefox is 'The connection was reset' (after idling for some time).

Also, in Eclipse, the URL does not work for me (via *Help -> Install New Software...*)

**Comment by anthonyanjorin** [comment]
I am also unable to install via the Eclipse update manager using ```http://files.idi.ntnu.no/publish/plantuml/repository/``` and get a:  ```Could not find ..``` 

This worked perfectly before (I believe even yesterday, certainly the day before yesterday).

**Comment by hallvard** [comment]
I checked with our local IT dept. and they discovered a setting in the firewall preventing access... I don't know why this happened, but the promised to fix it ASAP. Sorry for the problem, please confirm if it now works!

**Comment by RolandKluge** [comment]
Confirmed to work. Thank you for your help!
