### ISSUE TITLE
Example ordering of Participants not working

### ISSUE THREAD

**Issue by MaSven** [hallvard/plantuml#50]
On http://plantuml.com/sequence-diagram the example with the ordering seems not to work in the plugin. I always get:

> Syntax error?

The example is 
```
@startuml
participant Last order 30
participant Middle order 20
participant First order 10
@enduml
```

Eclipse version: 4.7.3

**Comment by hallvard** [comment]
I confirm this doesn't work in my version either. This depends on the plantuml library, I will have to upgrade it. Could you check when this feature and syntax was introduced?

**Comment by MaSven** [comment]
Sure will do.

**Comment by MaSven** [comment]
This [site](http://plantuml.com/news) suggests it was the version from 28.01.2018. So it must be this [trunk](https://sourceforge.net/p/plantuml/code/HEAD/tree/tags/plantuml-1.2018.1).

**Comment by hallvard** [comment]
That's pretty recent, I'm lagging behind in updating and releasing the Eclipse plugin. I'll try to fix this over Easter (which is an important holiday in Norway). Ideally I should automate updating the plantuml-lib plugin, so I don't need a release of the full plugin.

**Comment by MaSven** [comment]
The newest version would be 1.2018.2 i think. Yes some sort of automation could also help with pull request to see regression in the unit tests.

**Comment by MaSven** [comment]
I this possible ? Loading a jar dynamically in eclipse?

**Comment by hallvard** [comment]
I was thinking of making it easier to release a new plantuml.lib plugin independently of the main plantuml plugin, so you could use Eclipse's update functionality.

**Comment by MaSven** [comment]
Would it be helpful to have an automated integration tests that tests against the latest spec of plantuml? So you see a change sooner.

**Comment by hallvard** [comment]
I have some test of my own plugin, but there are few plantuml.jar (the library) related tests. It could be possible to run the plantuml.jar tests again in the context of the plantuml.lib, i.e. check whether the plantuml.lib plugin supports everything the newest version of plantuml.jar does. But I'm not sure it's worth it, as the fix to any failing tests would be to update to the newest plantuml.jar, and that should anyway happen soon after a release.

**Comment by ssnyder** [comment]
*bump*
Any chance we can get this pull request accepted and a new release of the plugin?  I would love to take advantage of the newer features now available.

**Comment by hallvard** [comment]
There has been all sorts of problems related to the build and files server, so now I'm trying out building locally (as before) travis and GitHub pages for update site. I've just now uploaded a new version 1.1.20 with PlantUml version 1.2018.9 that can be updated using hallvard.github.io/plantuml as update site URL. Could you try it out?
