### ISSUE TITLE
plantuml eclipse plugin not working in oxygen 4.7.3a

### ISSUE THREAD

**Issue by rasmusmk** [hallvard/plantuml#52]
After updating to newest eclipse (4.7.3a) plantuml stopped displaying my diagrams. It keeps showing a old one regardless of where I place my cursor in file with lots of different diagrams in comments.

**Comment by hallvard** [comment]
Is the editor the Java editor? If you open the PlantUml source view, does it update correctly?

**Comment by rasmusmk** [comment]
no it is c/c++ editor. No source in plantUML source view, just blank

**Comment by hallvard** [comment]
This means you have installed the standard C/C++ Development Tools (CDT), right? There is no special PlantUML support for the c/c++ editor, so it will rely on the generic support for the generic text editor. Could you please provide the file that gives the problem, so I can more easily reproduce it?

**Comment by rasmusmk** [comment]
I got it to work again. It was an error from my side. I had changed my startuml and enduml tags to use \ instead of @ because that was what the other doxygen commands where using. 
So using @startuml and @enduml still works for standard C/C++ Development Tools (CDT) oxygen 4.7.3a and loving it  :-)

**Comment by hallvard** [comment]
That's good to hear!
