### ISSUE TITLE
Cutomizing Class diagram output

### ISSUE THREAD

**Issue by yogendra-singh09** [hallvard/plantuml#57]
I am using plantuml source plugin to generate code. Most of the thing I have customized as per my requirement still some are left which I am not able to customize.

1) By default the plantUML source generate code as

BaseModel <|-- PreAssessmentProgressModel

But I want to show ":extends: in diagram.

PreAssessmentProgressModel ..> BaseModel : extends

2) The Attribute of the cass are written as

-String overallCompletion

Insite I want output as first attribute name and then type.

overallCompletion String

**Comment by hallvard** [comment]
In the next version, I will change the attribute syntax to proper UML (see #115). At some point I may support more extensive customisation of the generated PlantUML source.
