### ISSUE TITLE
add plugin to marketplace

### ISSUE THREAD

**Issue by anb0s** [hallvard/plantuml#58]
for easier finding and installation:
https://marketplace.eclipse.org/

**Comment by paulvi** [comment]
Second this!

https://marketplace.eclipse.org/addcontent

Most important to specify update site URL, and feature ID

**Comment by paulvi** [comment]
should appear soon, added https://marketplace.eclipse.org/content/ascii-uml-asciidoc-editor-plantuml-plugin (together with AsciiDoc Editor-based plantuml Editor )

see https://ascii-uml.github.io

ref https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/77

**Comment by paulvi** [comment]
Already visible https://marketplace.eclipse.org/content/ascii-uml-asciidoc-editor-plantuml-plugin

**Comment by paulvi** [comment]
@hallvard I cant transfer it and @ASCII-UML to you, when you wish

**Comment by hallvard** [comment]
I have added the PlantUML plugin to Eclipse Marketplace, now, should appear soon (if moderator approves).

**Comment by paulvi** [comment]
It is available as https://marketplace.eclipse.org/content/plantuml-plugin

**Comment by iRecursion** [comment]
it works fine for asciidoctor editor 2.2.0,
failure for PlantUML plugin or ASCII UML from eclipse marketplace

failure msg as follows:
HTTP Server 'Service Unavailable': http://hallvard.github.io/plantuml/compositeContent.xml
HttpComponents connection error response code 503.

Unable to connect to repository http://hallvard.github.io/plantuml/compositeContent.xml
Unable to connect to repository http://hallvard.github.io/plantuml/compositeContent.xml
Connect to hallvard.github.io:80 [hallvard.github.io/127.0.0.1, hallvard.github.io/0:0:0:0:0:0:0:1] failed: Connection refused: connect

eclipse version:
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)
Build id: 20200910-1200

could you provide such as a offline zip file(PlantUmlPlugin.zip),thanks!
