### ISSUE TITLE
Introduce support for .rst (sphinx) files

### ISSUE THREAD

**Issue by polybos** [hallvard/plantuml#6]
When creating sphinx-like reStructuredText (ReST/RST) files, e.g. for python documentation, it would be really nice to use the syntax of [sphinx plantuml extension](https://pypi.python.org/pypi/sphinxcontrib-plantuml) ('.. uml::') for plantuml and see it directly, like when using the _usual_ plantuml way ('@startuml', '@enduml').
May eclipse isn't the main platform for python, but it think some people use eclipse for documentation purpose.

**Comment by hallvard** [comment]
You should be able to implement a diagram text provider using the available extension point. If not, file a new issue.
