### ISSUE TITLE
Support all plantuml keywords

### ISSUE THREAD

**Issue by de-jcup** [hallvard/plantuml#60]
As mentioned in https://github.com/hallvard/plantuml/issues/59 a syntax highlighting for all plantuml keywords shall be added to the AsciiDoctorPlantUMLEditor

**Comment by hallvard** [comment]
I admit I didn't know about AsciiDoctorPlantUMLEditor, sound useful! But I'm curious why this issue is added to the plantuml repo? Is this implicitly a request to add AsciiDoctorPlantUMLEditor to the Eclipse PlantUML project and repo?

**Comment by paulvi** [comment]
PlantUML (AsciiDoctor) Editor appeared just week ago thank to Albert.

As there is some overlap/connection, as a user I would wish authors of plugin know about other author ideas.

**Comment by hallvard** [comment]
Closing this, as it overlaps with #59.

**Comment by de-jcup** [comment]
@hallvard  - Ups ... i am so sorry. I didn't mentioned that this was inside your repo :-o sorry...
