### ISSUE TITLE
Support PlantUML within Markdown

### ISSUE THREAD

**Issue by paulvi** [hallvard/plantuml#65]
There are several places where PlantUML within markdown is already supported

e.g. https://docs.gitlab.com/ee/administration/integration/plantuml.html

Code Example 

    ```puml
    	Mardown -> PlnatUML : hello
    ```

Please support within this plugin

Currently it does not

![image](https://user-images.githubusercontent.com/1614482/41190070-bb1d5e4a-6c0a-11e8-9e9f-a2a73079e79e.png)

**Comment by paulvi** [comment]
Currently requires `@startuml`

![image](https://user-images.githubusercontent.com/1614482/41190145-1ffe16d2-6c0c-11e8-842f-085a9e1bdb7a.png)

**Comment by hallvard** [comment]
OK, so the proposal is to support a wider set of prefix and suffix pairs.

**Comment by paulvi** [comment]
Yes,  prefix ```puml 
is already used on https://docs.gitlab.com/ee/administration/integration/plantuml.html

But the rest of ```puml line may have some additional parameters,
so actual PlantUML will start on next line.

Within ```puml  block can be other type of diagram, not UML, e.g. @startsalt and @endsalt pair,  
or @startdot and @enddot pair,  
so @startuml and @enduml pair becomes default.

For example a file with extension `.puml` and single line

    Bob->Alice : hello

is also valid PlantUML document/diagram, isn't it?

**Comment by hallvard** [comment]
It's easier to support special prefixes/suffixes when they're tied to a specific editor or file extension, like md or puml. So if it's OK with you, I'd rather add this as md- and puml-specific rules.

**Comment by paulvi** [comment]
As you prefer
