### ISSUE TITLE
Update site is down

### ISSUE THREAD

**Issue by dcendents** [hallvard/plantuml#69]
The update site has been down for at least 24 hours: http://files.idi.ntnu.no/publish/plantuml/repository/

Do you know what is happening?
Can the update site be hosted elsewhere?

Thanks

**Comment by psahrhage** [comment]
Having the same Issue here

**Comment by hallvard** [comment]
Thanks for reporting! I've been using the site myself and haven't had any problems, from work that is. Seems like it's a firewall issue, from home without VPN it refuses my attempts to connect. I'll report it and hope it'll be fixed tomorrow.

**Comment by hallvard** [comment]
It should be working now!

**Comment by psahrhage** [comment]
It does! Thank you very much

**Comment by anb0s** [comment]
@hallvard Thanks! It works now!

Just as idea: it's possible to use GitHub (gh-pages branch) as p2 update site --> easy to use, under source control together with project site. Example: https://github.com/anb0s/EasyShell/tree/gh-pages

**Comment by hallvard** [comment]
@anb0s Something like this? http://hallvard.github.io/plantuml/
Could you please try and see if it works?

**Comment by anb0s** [comment]
It would be good to have the Links that are generated by the GitHub page-generator:
e.g.: https://anb0s.github.io/EasyShell/

![image](https://user-images.githubusercontent.com/95811/44508362-4c559e80-a6ae-11e8-99fe-2ad6cc92437a.png)

so one can jump to the repo site...

**Comment by anb0s** [comment]
FYI: after updating to the test version 1.1.20 the PlantUML view shows:
![image](https://user-images.githubusercontent.com/95811/44508846-0dc0e380-a6b0-11e8-9b8f-18bcc59d0206.png)
I think it's not related to the new update site, but something in the packaging the new version 1.1.20...

**Comment by hallvard** [comment]
I've pushed a new version to gh-pages (with same version numbers, to you need to uninstall/install rather than update, and perhaps also reload the update site), could you try it out, please?

**Comment by anb0s** [comment]
> The download links are configured in the config.yml, right?
Yes, i think it's the "show_downloads: true", see: https://github.com/anb0s/EasyShell/blob/gh-pages/_config.yml

> I think NoSuchMethodError is thrown if somehow the old PlantUML library plugin is used instead of the new one (with version 1.2018.9). 
Ah, ok, just inform me, i will re-test...

**Comment by anb0s** [comment]
ok, will do :)

**Comment by anb0s** [comment]
now it looks good :+1: 
![image](https://user-images.githubusercontent.com/95811/44515883-ec69f280-a6c3-11e8-9b25-91a737da21c2.png)

![image](https://user-images.githubusercontent.com/95811/44515907-fb50a500-a6c3-11e8-843b-9d029cff78cf.png)
