### ISSUE TITLE
Update source code base of the upstream branch

### ISSUE THREAD

**Issue by seiferma** [hallvard/plantuml#7]
Hello,

please consider updating the source code base of this Plugin that originally came from @arnaudroques to a more recent version.

The reason for this is to include recent bugfixes like the one mentioned in [the bug report about the DiagramTextProvider extension point](http://plantuml.sourceforge.net/qa/?qa=1434/eclipse-plugin-export-package-sourceforge-plantuml-eclipse).

Best regards
seiferma

**Comment by hallvard** [comment]
This is fixed now.
