### ISSUE TITLE
Update site down?

### ISSUE THREAD

**Issue by RolandKluge** [hallvard/plantuml#71]
When I try to connect to the following update site, I get a timeout:

http://files.idi.ntnu.no/publish/plantuml/repository/content.xml.

**Comment by hallvard** [comment]
The update site has changed to **hallvard.github.io/plantuml** since the files.idi.ntnu.no server has been put behind a firewall. I'm sorry, but it wasn't my decision. I've informed Arnaud, but I haven't received a response, so I guess there hasn't been an announcement.

**Comment by RolandKluge** [comment]
@hallvard Thank you for the quick reply!
