### ISSUE TITLE
Eclipse update sites (old and new) not working

### ISSUE THREAD

**Issue by gorbachev** [hallvard/plantuml#76]
Neither the old Eclipse update site (http://files.idi.ntnu.no/publish/plantuml/repository) or the new one (http://hallvard.github.io/plantuml/) are working correctly. The plugin can not be installed on Eclipse from neither location.

**Comment by gorbachev** [comment]
Eclipse marketplace installation bundled with the ASCII UML Editor also has the same problem.

**Comment by hallvard** [comment]
It worked for me a minute ago, can you share details of what you did (e.g. was it an update or a fresh install) and how Eclipse responded. And perhaps try again, in case it was a GitHub glitch.

**Comment by hallvard** [comment]
The files are in a special branch used by GitHub pages, and the directory layout is that of ordinary p2 repos. You can't however, get a directory listing, but need to address individual files, like the Eclipse p2 mechanism does. E.g. the following address is to the main plugin jar: http://hallvard.github.io/plantuml/plantuml.eclipse/1.1.21/plugins/net.sourceforge.plantuml.eclipse_1.1.21.jar

**Comment by gorbachev** [comment]
Turns out it was the company firewall. hallvard.github.io was white listed, but apparently somehow improperly...all the deeplinks were being blocked. All good.

Thanks for your help, getting that direct link helped me get to the bottom of the issue.
