### ISSUE TITLE
PlantUML Project Class Diagram is not show picture as expected，The picture is not complete, it may be limited in size，especially when there are too many class files.

### ISSUE THREAD

**Issue by eastzq** [hallvard/plantuml#78]
eclipse version : oxygen
![image](https://user-images.githubusercontent.com/39581717/50505998-86e2a400-0ab1-11e9-9619-7422612b1c3d.png)

**Comment by hallvard** [comment]
I'm not sure this is the plugin's fault, or the underlying library's.

**Comment by arnaudroques** [comment]
If the limit is 4096 pixel, it may be related to PLANTUML_LIMIT_SIZE
See http://plantuml.com/faq

**Comment by eastzq** [comment]
@hallvard @arnaudroques thanks,This is because the picture of graphviz is limited to 4096px by default.
http://plantuml.com/faq
![image](https://user-images.githubusercontent.com/39581717/50578263-4ba9f180-0e72-11e9-9e01-327d7475c679.png)

**Comment by swm123456** [comment]
@hallvard @eastzq But how do you change this parameter for the Eclipse PlantUML plugin? Thanks in advance.
