### ISSUE TITLE
Change icon of https://marketplace.eclipse.org/content/plantuml-plugin ?

### ISSUE THREAD

**Issue by paulvi** [hallvard/plantuml#90]
Do you mind change icon of https://marketplace.eclipse.org/content/plantuml-plugin ?

Now it is default eclipse logo.

Can be planUML
http://plantuml.com/favicon.ico
![](http://plantuml.com/favicon.ico)

ref #58

**Comment by hallvard** [comment]
That icon is too small, instead I used http://s.plantuml.com/imgw/sequence-diagram-cb5gbgbc.png

**Comment by paulvi** [comment]
👍 

However, I don't see it yet on https://marketplace.eclipse.org/content/plantuml-plugin ...

**Comment by hallvard** [comment]
It may have been an issue with the aspect ratio, I've replaced it with scaled down version. Will find one that's not that fuzzy.

**Comment by paulvi** [comment]
![image](https://user-images.githubusercontent.com/1614482/55719599-36c09980-5a31-11e9-8385-d2829afd85a9.png)
