### ISSUE TITLE
Add ability to update the current diagram from view menu

### ISSUE THREAD

**Issue by steghoja** [hallvard/plantuml#92]
I am currently struggling with enabling the update of the current diagram from the menu of the view. The use case is as follows:

 * I am displaying a PlantUML diagram based on the selection in the IDE.
 * The PlantUML view menu has been extended by several options that influence the generated diagram via a custom `DiagramTextProvider`. 
 * The menu entries can be checked and if they are, an internal preference node is changed. The `DiagramTextProvider` then picks these preferences up the next time the diagram is rendered

Current behaviour:

 * The preference change takes effect when the user selects another view.

Desired behaviour:

 * The view updates immediately after the menu item has been clicked.

The problem is that  PlantUML currently has no option to regenerate the diagram with the last settings (as far as I can tell). The `currentPart` field of `AbstractDiagramSourceView` is private, so I can't use that when calling `updateDiagramText()`. Is there a way to accomplish what I want?

**Comment by hallvard** [comment]
Is this actually two separate issues?
- Plantuml should refresh the current diagram if the preferences change. This will potentially select a different DiagramTextProvider, since there now is a preference page for enabling/disabling them.
- You need a method in AbstractDiagramSourceView to force regeneration of the current diagram (for whatever reason), e.g. callable from a contributed menu action.

Both these sound reasonable!

**Comment by steghoja** [comment]
I agree with your analysis. It's relatively easy to add a listener for changes of specific preference nodes like this:
```
// A preference change listener to update the view
IPreferenceChangeListener updateViewOnPreferenceChange = new IPreferenceChangeListener() {
	@Override
	public void preferenceChange(PreferenceChangeEvent event) {
		// Update the diagram somehow
            	updateCurrentDiagram();
	}
};

IEclipsePreferences somePreference = InstanceScope.INSTANCE.getNode("org.eclipse.something.SomePreference");
		somePreference.addPreferenceChangeListener(updateViewOnPreferenceChange);
```

The main need is to have an `updateCurrentDiagram()` method. That could probably look something like this (untested):

```
public void updateCurrentDiagram() {
	updateDiagramText(true, currentPart, null);
}
```

**Comment by hallvard** [comment]
Is it an option to use the PlantUML plugin's preference store instead of a preference node? Then I think you can listen to the whole store with a property change listener. That simpler than finding all preference nodes related to PlantUML and listening to them.

**Comment by steghoja** [comment]
Sure, that should also work. I think we are thinking of slightly different use cases: you are thinking of updating the diagram when a PlantUML preference changes, while I am thinking of updating the diagram when my own preference changes. What I am doing is to extend `PlantUmlView` and registering my own `IPreferenceChangeListener` in a overriden version of `createPartControl()`, but I need a *public* method in `AbstractDiagramSourceView` or `PlantUmlView` to update the diagram. Insofar, I fully agree with you that these are two separate issues:

1. Provide a method to update the current diagram.
2. Make sure that the changes in the PlantUML preferences are immediately reflected in the view.

While I am mostly interested in number 1, number 2 is easy once number 1 is in place. The only request I have is to make the method that performs the update part of the API.

**Comment by hallvard** [comment]
I'll add this issue to the next milestone. So far I haven't been explicit about what API is "official" and what is internal, but this case shows I will need to, at least for the requested method.

**Comment by hallvard** [comment]
I've added a public updateDiagramText() method, that recomputes the diagram from the currently active editor or view.

**Comment by steghoja** [comment]
Thanks Hallvard, but this doesn't quite address my use case. As pointed out in my comment above, I need a version of `updateDiagramText()` that is public and that lets me update the diagram based on the part that was last used. Right now, since `updateDiagramText()` is defined as

```
public void updateDiagramText() {
	updateDiagramText(true, null, null);
}
```

the `IWorkbenchPart` from which the diagram is generated is updated. Since I make the change in the preferences from a view (actually, a derivative of `PlantUmlView`, the active part changes and the updates are, again, not visible.

I will submit a pull request with a suggestion on how to address this.
