### ISSUE TITLE
Scaling preview results in pixel 

### ISSUE THREAD

**Issue by SieDa** [hallvard/plantuml#94]
Scaling the created diagram in the preview area results in pixels on fonts and lines and sometimes is hard to read in different than 100% presentations. 
Why does that happen, as the result of an export is always perfect, especially the svg output is able to scale up. I added a simple example.
Is this related to eclipse or just how plantuml works or "just" using the wrong stuff to show (SVG)? 
![grafik](https://user-images.githubusercontent.com/30753914/58536357-9563f180-81f0-11e9-987d-9299ecc79754.png)
![grafik](https://user-images.githubusercontent.com/30753914/58536381-aad91b80-81f0-11e9-94ca-01c3e3f78b7c.png)

On top, sometimes it would be nice to have an additional scale button for the page-width / -height.

**Comment by hallvard** [comment]
We only scale the generated png image (pixels), we don't generate SVG and (re)render.

**Comment by hallvard** [comment]
We could provide an SVG viewer instead of using the image. But that should go into another issue.

**Comment by hallvard** [comment]
This is something I'm considering. A very simple solution is to provide a web-based viewer in an embedded browser component, that can show the svg. This shouldn't be much work, at least not for the single diagram case.
