### ISSUE TITLE
Cannot install on Eclipse 2019.06

### ISSUE THREAD

**Issue by sorenfriis** [hallvard/plantuml#96]
On Eclipse 2019.06 (CDT edition) I cannot install the PlantUML plugin.
These two parts refuse to install:
- PlantUML Ecore Feature
- PlantUML Feature

![image](https://user-images.githubusercontent.com/18438285/64117540-b90d7980-cd95-11e9-9dc0-4159b215dd71.png)

![image](https://user-images.githubusercontent.com/18438285/64117804-6e403180-cd96-11e9-8dba-4d2a863f5d1d.png)

**Comment by hallvard** [comment]
Hmm, I've just installed it on top of the DSL tools package, so there must be an issue with the C/C++ package. Can you somehow find out what the conflict is? E.g. select "Show original error and build my own solution"?

**Comment by sorenfriis** [comment]
Here is the content of the "Details" window after selecting "Show original error and build my own solution":

> Cannot complete the install because one or more required items could not be found.
  Software being installed: PlantUML Feature 1.1.23 (net.sourceforge.plantuml.feature.feature.group 1.1.23)
  Missing requirement: PlantUML Java Support 1.1.23 (net.sourceforge.plantuml.jdt 1.1.23) requires 'java.package; org.eclipse.jdt.internal.debug.ui.actions 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: PlantUML Feature 1.1.23 (net.sourceforge.plantuml.feature.feature.group 1.1.23)
    To: org.eclipse.equinox.p2.iu; net.sourceforge.plantuml.jdt [1.1.23,1.1.23]

**Comment by hallvard** [comment]
Yes, the JDT support is part of the main PlantUML feature. I'll take a look at this issue as part of next release.

**Comment by sorenfriis** [comment]
It turns out, that I was missing the main eclipse repository in my "Available Software Sites".
After adding `https://download.eclipse.org/releases/2019-06/` it was able to resolve the dependencies and install correctly.
Thanks for your guiding - ofcourse it would be nice if it would be able to install directly on a clean CDT install.

**Comment by hallvard** [comment]
Thanks for the info! It may still make sense to split into more features.

**Comment by kapadiab** [comment]
I followed this step and it worked for that instance however eclipse was not able to launch after this.
